server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
spring:
  task:
    execution:
      pool:
        core-size: 10
        max-size: 100
        queue-capacity: 1000
        keep-alive: 300s
      thread-name-prefix: defaultAsync-
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

